// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVPWLrsSqIhEVTmtrpWazkmFIiZZ_Lro',
    appId: '1:688237186185:web:1cb89507fd9840eda40a58',
    messagingSenderId: '688237186185',
    projectId: 'ejemplo-ac741',
    authDomain: 'ejemplo-ac741.firebaseapp.com',
    storageBucket: 'ejemplo-ac741.appspot.com',
    measurementId: 'G-F9K94Q0K8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1y09Cy8920ZsCVTIJ8D46TsaqGhuQIk',
    appId: '1:688237186185:android:e50191602534a977a40a58',
    messagingSenderId: '688237186185',
    projectId: 'ejemplo-ac741',
    storageBucket: 'ejemplo-ac741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8jUmuh6xIj4LSuQaJF5QcEjczuTan-AM',
    appId: '1:688237186185:ios:0e7469bad8e9c6fca40a58',
    messagingSenderId: '688237186185',
    projectId: 'ejemplo-ac741',
    storageBucket: 'ejemplo-ac741.appspot.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8jUmuh6xIj4LSuQaJF5QcEjczuTan-AM',
    appId: '1:688237186185:ios:0e7469bad8e9c6fca40a58',
    messagingSenderId: '688237186185',
    projectId: 'ejemplo-ac741',
    storageBucket: 'ejemplo-ac741.appspot.com',
    iosBundleId: 'com.example.prueba',
  );
}
